spring:
  application:
    name: rag-backend

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: "jdbc:postgresql://localhost:15432/appdb"
    username: "appTest"
    password: ""
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen3:4b
      embedding:
        options:
          model: nomic-embed-text:latest

server:
  port: 8080

app:
  collect:
    kcisa:
      base-url: https://api.kcisa.kr
      endpoint: /openapi/service/rest/meta14/getNLCF031801
      service-key: 8d897deb-f057-4a73-b042-474b0b73954f
      num-of-rows: 100
      response-type: json
  rag:
    chunk-size: 500
    chunk-overlap: 50
    top-k: 10
    embedding:
      dimensions: 64
      title-weight: 0.7

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.example.rag.collect.dto, com.example.rag.collect.model, com.example.rag.rag.model
  configuration:
    map-underscore-to-camel-case: true